from fastapi import FastAPI, File, UploadFile, Response
from fastapi.middleware.cors import CORSMiddleware
from deepface import DeepFace
import cv2
import numpy as np
import os
import tempfile
from fpdf import FPDF
from datetime import datetime
import json

app = FastAPI()

# Enable CORS for the frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {"message": "EmoDetect AI API is active (DeepFace)"}

@app.post("/process-image")
async def process_image(file: UploadFile = File(...)):
    # Save the uploaded file to a temporary location
    temp_fd, temp_path = tempfile.mkstemp(suffix=".jpg")
    try:
        contents = await file.read()
        with os.fdopen(temp_fd, 'wb') as tmp:
            tmp.write(contents)
        
        # Analyze the image for emotions using DeepFace
        # enforce_detection=False prevents crash if no face is found
        results = DeepFace.analyze(
            img_path=temp_path, 
            actions=['emotion'],
            enforce_detection=False,
            detector_backend='opencv' # Fastest for real-time
        )
        
        # DeepFace returns a list of results (one for each face detected)
        if results and len(results) > 0:
            dominant_emotion = results[0]['dominant_emotion'].capitalize()
            
            # Map to frontend expected labels
            mappings = {
                "Surprise": "Surprised",
                "Disgust": "Disgusted"
            }
            dominant_emotion = mappings.get(dominant_emotion, dominant_emotion)
            
            confidence = int(results[0]['emotion'][results[0]['dominant_emotion']])
            
            print(f"Detected: {dominant_emotion} ({confidence}%)")
            return [dominant_emotion, confidence]
        
        return ["Neutral", 0] # Fallback if no face detected

    except Exception as e:
        print(f"Error processing image: {str(e)}")
        return ["Neutral", 0]
    finally:
        # Clean up the temporary file
        if os.path.exists(temp_path):
            os.remove(temp_path)

@app.post("/generate-report")
async def generate_report(data: dict):
    try:
        pdf = FPDF()
        pdf.add_page()
        
        # Title
        pdf.set_font("Arial", 'B', 24)
        pdf.set_text_color(108, 99, 255) # Primary color
        pdf.cell(0, 20, "EmoDetect Session Report", ln=True, align='C')
        
        # Metadata
        pdf.set_font("Arial", size=12)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
        pdf.ln(10)
        
        # Summary Section
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "Executive Summary", ln=True)
        pdf.set_font("Arial", size=12)
        pdf.cell(0, 10, f"Total Detections: {data.get('totalDetections', 0)}", ln=True)
        pdf.cell(0, 10, f"Average Confidence: {data.get('avgConfidence', '0%')}", ln=True)
        pdf.cell(0, 10, f"Dominant Emotion: {data.get('dominantEmotion', '-')}", ln=True)
        pdf.ln(10)
        
        # Emotion Distribution Table
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "Emotion Distribution", ln=True)
        
        # Table Header
        pdf.set_font("Arial", 'B', 12)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(60, 10, "Emotion", 1, 0, 'C', True)
        pdf.cell(60, 10, "Frequency", 1, 0, 'C', True)
        pdf.cell(70, 10, "Avg Confidence", 1, 1, 'C', True)
        
        # Table Data
        pdf.set_font("Arial", size=12)
        counts = data.get('emotionCounts', {})
        confidences = data.get('emotionConfidences', {})
        
        for emotion, count in counts.items():
            avg_conf = "0%"
            if emotion in confidences and confidences[emotion]:
                avg_conf = f"{int(sum(confidences[emotion]) / len(confidences[emotion]))}%"
            
            pdf.cell(60, 10, emotion, 1)
            pdf.cell(60, 10, str(count), 1, 0, 'C')
            pdf.cell(70, 10, avg_conf, 1, 1, 'C')
            
        # Footer
        pdf.set_y(-30)
        pdf.set_font("Arial", 'I', 8)
        pdf.cell(0, 10, "Generated by EmoDetect AI - Advanced Real-time Emotion Analysis System", 0, 0, 'C')
        
        # Output to temporary file
        temp_pdf = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
        pdf.output(temp_pdf.name)
        
        with open(temp_pdf.name, "rb") as f:
            pdf_content = f.read()
            
        os.remove(temp_pdf.name)
        
        return Response(
            content=pdf_content,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=EmoDetect_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"}
        )
    except Exception as e:
        print(f"Error generating report: {str(e)}")
        return {"error": str(e)}

if __name__ == "__main__":
    import uvicorn
    # Pre-load the model to avoid delay on first request
    print("Starting server...")
    # try:
    #     DeepFace.build_model("Emotion")
    # except:
    #     pass
    uvicorn.run(app, host="0.0.0.0", port=8000)
